experiment:
  description: VAE-WGAN with explicit shifts | with hinge loss
  output_location: /data/namrata/models/scene-reconstruction
  load: /data/namrata/models/scene-reconstruction/vae-gan-w_3-2-5/checkpoints/vae_gan_60.pth
  init_opt: False

data:
  sources:
    - kitti360_semantic_adv:
        train: /data/namrata/kitti-360/data_2d_semantics/train
        val: /data/namrata/kitti-360/data_2d_semantics/val
        test: path to folder containing test data
        batch_size: 32
        sample_size: null
        crop_size: 224
  num_workers: 10

model:
  model_key: shift_gan
  trainer_key: shift_gan_trainer
  modes:
    - train
    - val
  epochs: 1000
  n_classes: 3
  reconstruction_loss: cross_entropy
  adv_loss: wasserstein_loss
  loss_weights:
    reconstruction: [0.3, 0.2, 0.5]
    kld: [0.0001, 0.0001, 0.0001]
    bin: 0.0
    adv: 1
    hinge: 0.1
  shift_classes: [2]
  network:
    encoder_pre:
      - Conv2d:
          in_channels: 1
          out_channels: 32
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - Conv2d:
          in_channels: 32
          out_channels: 64
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - Conv2d:
          in_channels: 64
          out_channels: 64
          kernel_size: 3
          stride: 2
        activation: LeakyReLU

    encoder_post:
      - MaxPool2d:
          kernel_size: 2
          stride: 2
      - Conv2d:
          in_channels: 128
          out_channels: 256
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - Conv2d:
          in_channels: 256
          out_channels: 512
          kernel_size: 3
          stride: 2
        activation: LeakyReLU

    encoder_fc:
      - Linear:
          in_features: 2048
          out_features: 1024
        activation: LeakyReLU
        dropout: 0.5
      - Linear:
          in_features: 1024
          out_features: 512
        activation: LeakyReLU
        dropout: 0.5

    fc_mu:
      - Linear:
          in_features: 512
          out_features: 256

    fc_var:
      - Linear:
          in_features: 512
          out_features: 256

    shift_mu:
      - Linear:
          in_features: 512
          out_features: 128
      - Linear:
          in_features: 128
          out_features: 2
        activation: Tanh

    shift_var:
      - Linear:
          in_features: 512
          out_features: 128
      - Linear:
          in_features: 128
          out_features: 2
        activation: Tanh

    decoder_fc:
      - Linear:
          in_features: 256
          out_features: 512
        activation: LeakyReLU
      - Linear:
          in_features: 512
          out_features: 1024
        activation: LeakyReLU
      - Linear:
          in_features: 1024
          out_features: 2048
        activation: LeakyReLU

    decoder_pre:
      - ConvTranspose2d:
          in_channels: 512
          out_channels: 256
          kernel_size: 3
          stride: 3
        activation: LeakyReLU
      - ConvTranspose2d:
          in_channels: 256
          out_channels: 128
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - ConvTranspose2d:
          in_channels: 128
          out_channels: 64
          kernel_size: 3
          stride: 2
        activation: LeakyReLU

    decoder_post:
      - Upsample:
          scale_factor: 2
      - ConvTranspose2d:
          in_channels: 64
          out_channels: 32
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - ConvTranspose2d:
          in_channels: 32
          out_channels: 1
          kernel_size: 3
          stride: 2
      - Upsample:
          size: 224

    discriminator:
      - Conv2d:
          in_channels: 3
          out_channels: 32
          kernel_size: 3
          stride: 2
        activation: ReLU
      - Conv2d:
          in_channels: 32
          out_channels: 64
          kernel_size: 3
          stride: 2
        activation: ReLU
      - Conv2d:
          in_channels: 64
          out_channels: 128
          kernel_size: 3
          stride: 2
        activation: ReLU
      - MaxPool2d:
          kernel_size: 2
          stride: 2
      - Conv2d:
          in_channels: 128
          out_channels: 256
          kernel_size: 3
          stride: 2
        activation: ReLU
      - Conv2d:
          in_channels: 256
          out_channels: 512
          kernel_size: 3
          stride: 2
        activation: ReLU
    discriminator_fc:
      - Linear:
          in_features: 2048
          out_features: 1024
        activation: ReLU
        dropout: 0.5
      - Linear:
          in_features: 1024
          out_features: 1
        activation: Tanh

  optimizers:
    vae:
      Adam:
        lr: 0.0001
        weight_decay: 0.0001
    disc:
      Adam:
        lr: 0.0001
        weight_decay: 0.0001