experiment:
  description: Markovian sequential VAEs
  output_location: /data/namrata/models/scene-reconstruction
  load: null
  init_opt: False

data:
  sources:
    - kitti360_semantic_1hot:
        train: /data/namrata/kitti-360/data_2d_semantics/train
        val: /data/namrata/kitti-360/data_2d_semantics/val
        test: path to folder containing test data
        batch_size: 32
        sample_size: 1000
        crop_size: 224
  num_workers: 10

model:
  model_key: markov_vae
  trainer_key: markov_vae_trainer
  modes:
    - train
    - val
  epochs: 100
  n_classes: 3
  reconstruction_loss: cross_entropy
  loss_weights:
    reconstruction: [0.1, 0.2, 0.7]
    kld: [0.0001, 0.0001, 0.0001]
    bin: 0.0
  network:
    encoder_pre:
      - Conv2d:
          in_channels: 1
          out_channels: 32
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - Conv2d:
          in_channels: 32
          out_channels: 64
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - Conv2d:
          in_channels: 64
          out_channels: 64
          kernel_size: 3
          stride: 2
        activation: LeakyReLU

    encoder_post:
      - MaxPool2d:
          kernel_size: 2
          stride: 2
      - Conv2d:
          in_channels: 128
          out_channels: 256
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - Conv2d:
          in_channels: 256
          out_channels: 512
          kernel_size: 3
          stride: 2
        activation: LeakyReLU

    encoder_fc:
      - Linear:
          in_features: 2048
          out_features: 1024
        activation: LeakyReLU
        dropout: 0.5
      - Linear:
          in_features: 1024
          out_features: 512
        activation: LeakyReLU
        dropout: 0.5

    fc_mu:
      - Linear:
          in_features: 512
          out_features: 32
        activation: LeakyReLU

    fc_var:
      - Linear:
          in_features: 512
          out_features: 32
        activation: LeakyReLU

    decoder_fc:
      - Linear:
          in_features: 32
          out_features: 512
        activation: LeakyReLU
      - Linear:
          in_features: 512
          out_features: 1024
        activation: LeakyReLU
      - Linear:
          in_features: 1024
          out_features: 2048
        activation: LeakyReLU

    decoder_pre:
      - ConvTranspose2d:
          in_channels: 512
          out_channels: 256
          kernel_size: 3
          stride: 3
        activation: LeakyReLU
      - ConvTranspose2d:
          in_channels: 256
          out_channels: 128
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - ConvTranspose2d:
          in_channels: 128
          out_channels: 64
          kernel_size: 3
          stride: 2
        activation: LeakyReLU

    decoder_post:
      - Upsample:
          scale_factor: 2
      - ConvTranspose2d:
          in_channels: 64
          out_channels: 32
          kernel_size: 3
          stride: 2
        activation: LeakyReLU
      - ConvTranspose2d:
          in_channels: 32
          out_channels: 1
          kernel_size: 3
          stride: 2
      - Upsample:
          size: 224
        activation: Sigmoid

  optimizers:
    vae:
      Adam:
        lr: 0.001
        weight_decay: 0.0001